version: '3.8'
services:
  app:
    build: .
    image: ${PROJECT_NAME}-app:${ENV_NAME}
    container_name: ${PROJECT_NAME}-app:${ENV_NAME}
    restart: always
    ports:
      - '3000:3000'
    environment:
      TTL: ${TTL}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      REGION: ${REGION}
      THRESHOLD: ${THRESHOLD}
      PUBSUB_TOPIC: ${PUBSUB_TOPIC}
      ENV_NAME: ${ENV_NAME}
    volumes:
      - ./credentials:/app/credentials

   


