version: '3.8'
services:
  app:
    build: .
    image: gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}-app:${ENV_NAME}
    container_name: ${PROJECT_NAME}-app-${ENV_NAME}
    restart: always
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TTL: ${TTL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${PROJECT_NAME}-db-${ENV_NAME}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      REGION: ${REGION}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      THRESHOLD: ${THRESHOLD}
      PUBSUB_TOPIC: ${PUBSUB_TOPIC}
      ENV_NAME: ${ENV_NAME}
    volumes:
      - ./credentials:/app/credentials

   


